services:
  - type: web
    name: backend
    runtime: node
    rootDir: ./backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
  - type: static
    name: frontend
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    publishPath: ./build
